auto:           true
pygments:       true
permalink:      pretty
paginate:       5

title:          FLTK.pm
feed:           atom.xml
sitemap:        sitemap.xml
description:    "Perl interface to the Fast Light Toolkit"
baseurl:        http://sanko.github.com/fltk-perl/

author:
    name:       Sanko Robinson
    email:      sanko@cpan.org

disqus:
    id:         sanko

css:
    - ~stylesheets/reset.css
    - ~stylesheets/layout.css
    - ~stylesheets/typography.css
    - ~stylesheets/paint.css
    - ~stylesheets/discus-comments.css
    - ~stylesheets/testing.css
    - ~stylesheets/syntax.css

js: []

google:
    analytics:  UA-683755-2
