source:         .
destination:    ./_site/perl-fltk2
lsi:            false
pygments:       true

auto:           true
permalink:      pretty
paginate:       5

title:          FLTK - Perl Bindings to the Fast Light Toolkit
feed:           atom.xml
sitemap:        sitemap.xml
description:    "Perl bindings to the Fast Light Toolkit"

author:
    name:       Sanko Robinson
    email:      sanko@cpan.org

disqus:
    id:         sanko

css:
    #- ~stylesheets/reset.css
    #- ~stylesheets/layout.css
    #- ~stylesheets/typography.css
    #- ~stylesheets/paint.css
    #- ~stylesheets/discus-comments.css
    #- ~stylesheets/testing.css
    #- ~stylesheets/syntax.css
    - stylesheets/reset.css
    - stylesheets/index.css
js: []

google:
    analytics:  UA-683755-6

system:
    layouts:
        page:
            settings: { }
    categories:
        page:
            layout:     page
            display:    true

