=pod

=for license Artistic License 2.0 | Copyright (C) 2009 by Sanko Robinson

=for author Sanko Robinson <sanko@cpan.org> - http://sankorobinson.com/

=for git $Id$ for got=

=head1 NAME

FLTK::Todo - TODO list for Perl module FLTK

=head1 High priorities

=over

=item * Flag all GL-related stuff in apidoc

=item * Creating new callbacks leaks memory

=item * Finish all widgets, etc.

=back

=head1 Short term goals

=over

=item F<xs/run.xsi>

=over

=item * C<has_timeout()>, C<remove_timeout(...)>, C<repeat_timeout(...)> do
not work because the SV* I shove into the callback are not equal from the
perspective of C++.

=item * C<remove_check(...)>, et. al do not work for the reasons stated above

=item * C<remove_idle(...)>, et. al do not work for the reasons stated above

=item * C<add_fd(...)>, C<add_fd(...)>, and C<remove_fd(...)>

=item * C<lock()>, C<unlock()>, C<awake([...])>, C<thread_message()>,
C<in_main_thread()>

=back

=item F<fltk/events.h>

=over

=item * C<add_event_handler>

=back

=item Anti-perl-isms

=over

=item * L<C<Color::split_color( color, r, g, b )>|FLTK::Color/"split_color">
sets the values of C<r,g,b> which is very un-perl. I'd rather return an AV*
with the values of C<r,g,b>.

=back

=item Subclass-able L<Image|FLTK::Image> and child classes

=back

=head1 Long term goals

=over

=item * L<FLTK::FileIcon|FLTK::FileIcon>

=item * GL stuff

=over

=item GLUT emulation

=item OpenGL Optimizer stuff in GlWindow subclass

=back

=back

=head1 Production Ready Perl 6 (read 'One of these days')

=over

=item * Somehow control order of object destruction...

...to kill child elements first. This way, I can clean up perl objects as they
go out of scope.

=back

=cut
