=pod

=head1 NAME

FLTK::Monitor - The subclass of C<FLTK::Widget>

=head1 Description

C<FLTK::Monitor>s describe one of the monitors (screens) connected to the
system. You can ask for one by position with L<C<find ( )>|/"find()">,
ask for all of them with L<C<list ( )>|/"list()">, and ask for a fake one
that surrounds all of them with L<C<all ( )>|/"all()">. You then look in
the structure to get information like the size and bit depth.

=head1 Functions

TODO

=head1 Disclaimer

This document and the specification behind it are subject to change.
All modifications will be documented in the Changes file included with
this distribution.  All versions of this file can be found in the
project's git repository.

=head1 Author

Sanko Robinson <sanko@cpan.org> - http://sankorobinson.com/

CPAN ID: SANKO

=head1 License and Legal

Copyright (C) 2009 by Sanko Robinson E<lt>sanko@cpan.orgE<gt>

This program is free software; you can redistribute it and/or modify
it under the terms of The Artistic License 2.0.  See the F<LICENSE>
file included with this distribution or
http://www.perlfoundation.org/artistic_license_2_0.  For
clarification, see http://www.perlfoundation.org/artistic_2_0_notes.

When separated from the distribution, all POD documentation is covered
by the Creative Commons Attribution-Share Alike 3.0 License.  See
http://creativecommons.org/licenses/by-sa/3.0/us/legalcode.  For
clarification, see http://creativecommons.org/licenses/by-sa/3.0/us/.

=for git $Id: Monitor.pod a404412 2009-03-24 05:36:10Z sanko@cpan.org $ forgot=

=cut
